export const GET_MENTORS = 'GET_MENTORS'
export const RECIEVED_GET_MENTORS = 'RECIEVED_GET_MENTORS'
export const FAILURE_GET_MENTORS = 'FAILURE_GET_MENTORS'

export const CREATE_MENTOR = 'CREATE_MENTOR'
export const RECIEVED_NEW_MENTOR = 'RECIEVED_NEW_MENTOR'
export const FAILURE_CREATE_MENTOR = 'FAILURE_CREATE_MENTOR'

export const DELETE_MENTOR = 'DELETE_MENTOR'
export const SUCCESS_DELETE_MENTOR = 'SUCCESS_DELETE_MENTOR'
export const FAILURE_DELETE_MENTOR = 'FAILURE_DELETE_MENTOR'


export const UPDATE_MENTOR = 'UPDATE_MENTOR'
export const SUCCESS_UPDATE_MENTOR = 'SUCCESS_UPDATE_MENTOR'
export const FAILURE_UPDATE_MENTOR = 'FAILURE_UPDATE_MENTOR'

export const SEARCH_LESSONS = 'SEARCH_LESSONS'
export const SUCCESS_SEARCH_LESSONS = 'SUCCESS_SEARCH_LESSONS'
export const FAILURE_SEARCH_LESSONS = 'FAILURE_SEARCH_LESSONS'

export const AUTO_COMPLITE = 'AUTO_COMPLITE'
export const SUCCESS_AUTO_COMPLITE = 'SUCCESS_AUTO_COMPLITE'
export const FAILURE_AUTO_COMPLITE = 'FAILURE_AUTO_COMPLITE'

export const GET_ACTIVE_GROUPS = 'GET_ACTIVE_GROUPS'
export const RECIEVED_ACTIVE_GROUPS = 'RECIEVED_ACTIVE_GROUPS'
export const FAILURE_GET_ACTIVE_GROUPS = 'FAILURE_GET_ACTIVE_GROUPS'

export const GET_ROOMS = 'GET_ROOMS'
export const RECIEVED_ROOMS = 'RECIEVED_ROOMS'
export const FAILURE_GET_ROOMS = 'FAILURE_GET_ROOMS'


export const GET_COURSES = 'GET_COURSES'
export const RECIEVED_COURSES = 'RECIEVED_COURSES'
export const FAILURE_GET_COURSES = 'FAILURE_GET_COURSES'

export const CREATE_LESSON_IN_WEEK = 'CREATE_LESSON_IN_WEEK'
export const RECIEVED_NEW_LESSON_IN_WEEK = 'RECIEVED_NEW_LESSON_IN_WEEK'
export const FAILURE_CREATE_LESSON_IN_WEEK = 'FAILURE_CREATE_LESSON_IN_WEEK'

export const CREATE_BUSY_IN_WEEK = 'CREATE_BUSY_IN_WEEK'
export const RECIEVED_NEW_BUSY_IN_WEEK = 'RECIEVED_NEW_BUSY_IN_WEEK'
export const FAILURE_CREATE_BUSY_IN_WEEK = 'FAILURE_CREATE_BUSY_IN_WEEK'

export const CREATE_GROUP = 'CREATE_GROUP '
export const RECIEVED_NEW_GROUP = 'RECIEVED_NEW_GROUP'
export const FAILURE_CREATE_GROUP  = 'FAILURE_CREATE_GROUP'

export const DELETE_ACTIVE_GROUP = 'DELETE_ACTIVE_GROUP'
export const SUCCESS_DELETE_ACTIVE_GROUP  = 'SUCCESS_DELETE_ACTIVE_GROUP'
export const FAILURE_DELETE_ACTIVE_GROUP = 'FAILURE_DELETE_ACTIVE_GROUP'


export const UPDATE_ACTIVE_GROUP  = 'UPDATE_ACTIVE_GROUP'
export const SUCCESS_UPDATE_ACTIVE_GROUP = 'SUCCESS_UPDATE_ACTIVE_GROUP'
export const FAILURE_UPDATE_ACTIVE_GROUP = 'FAILURE_UPDATE_ACTIVE_GROUP'

export const GET_GROUPS = 'GET_GROUPS'
export const RECIEVED_GET_GROUPS = 'RECIEVED_GET_GROUPS'
export const FAILURE_GET_GROUPS  = 'FAILURE_GET_GROUPS'


export const DELETE_LESSON = 'DELETE_LESSON'
export const SUCCESS_DELETE_LESSON = 'SUCCESS_DELETE_LESSON'
export const FAILURE_DELETE_LESSON = 'FAILURE_DELETE_LESSON'


export const UPDATE_LESSON = 'UPDATE_LESSON'
export const SUCCESS_UPDATE_LESSON = 'SUCCESS_UPDATE_LESSON'
export const FAILURE_UPDATE_LESSON = 'FAILURE_UPDATE_LESSON'

export const DELETE_BUSY = 'DELETE_BUSY'
export const SUCCESS_DELETE_BUSY = 'SUCCESS_DELETE_BUSY'
export const FAILURE_DELETE_BUSY= 'FAILURE_DELETE_BUSY'


export const UPDATE_BUSY = 'UPDATE_BUSY'
export const SUCCESS_UPDATE_BUSY = 'SUCCESS_UPDATE_BUSY'
export const FAILURE_UPDATE_BUSY = 'FAILURE_UPDATE_BUSY'